version: "3.9"
services:
  node-backend:
    build: .
    ports:
      - "2000:2000"
    volumes:
      - .:/usr/src/app
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./db:/usr/src/db
    ports:
      - 27017:27017
    depends_on:
      - node-backend
