version: "3.9"
services:
  node-backend:
    build: .
    command: bash -c "npm i && npm start"
    ports:
      - "2000:2000"
    volumes:
      - ./:/usr/src/app
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/usr/src/db
